import json
from typing import Any
from google import genai
from google.genai import types
from app.config import GEMINI_API_KEY, GEMINI_MODEL
from app.services.catalog import fallback_home, fallback_party, fallback_jewelry, product_url

_client = genai.Client(api_key=GEMINI_API_KEY) if GEMINI_API_KEY else None

SYSTEM_RULES = """
You are PocketSmart AI, a budget-aware recommendation assistant.
Return ONLY valid JSON with this exact shape:
{
  "summary": "string",
  "allocation": {"category": number},
  "recommendations": [
    {"title":"string","category":"string","estimated_price":number,"platform":"Amazon|Flipkart|IKEA|Swiggy|Zomato|OYO","reason":"string","url":"string"}
  ],
  "tips": ["string"]
}
Rules:
- Stay within the user's stated total budget.
- Prices are estimates, not live prices.
- Platform links are search links, not verified live inventory.
- Do not claim a product is currently in stock.
- Prefer 4-8 recommendations.
- Use Indian rupees.
"""


def _call(prompt: str, image_bytes: bytes | None = None, mime_type: str | None = None) -> dict[str, Any]:
    if not _client:
        raise RuntimeError("GEMINI_API_KEY is not configured")
    contents: list[Any] = [SYSTEM_RULES + "\n\n" + prompt]
    if image_bytes and mime_type:
        contents.append(types.Part.from_bytes(data=image_bytes, mime_type=mime_type))
    response = _client.models.generate_content(
        model=GEMINI_MODEL,
        contents=contents,
        config=types.GenerateContentConfig(
            temperature=0.4,
            response_mime_type="application/json",
        ),
    )
    text = response.text or "{}"
    return json.loads(text)


def _normalize(raw: dict, planner: str, budget: float) -> dict:
    recs = []
    for item in raw.get("recommendations", []):
        platform = str(item.get("platform", "Amazon"))
        if platform not in {"Amazon", "Flipkart", "IKEA", "Swiggy", "Zomato", "OYO"}:
            platform = "Amazon"
        title = str(item.get("title", "Recommendation"))[:120]
        recs.append({
            "title": title,
            "category": str(item.get("category", planner)),
            "estimated_price": max(0.0, float(item.get("estimated_price", 0))),
            "platform": platform,
            "reason": str(item.get("reason", "Budget-aligned option."))[:500],
            "url": product_url(platform, title),
        })
    return {
        "planner": planner,
        "budget": budget,
        "summary": str(raw.get("summary", "Personalized recommendations generated by Gemini.")),
        "allocation": {str(k): float(v) for k, v in (raw.get("allocation") or {}).items()},
        "recommendations": recs[:8],
        "tips": [str(x) for x in raw.get("tips", [])][:8],
        "source": "gemini",
    }


def generate_home(data: dict) -> dict:
    prompt = f"Create a home interior plan. User data: {json.dumps(data)}"
    try:
        return _normalize(_call(prompt), "home", float(data["budget"]))
    except Exception:
        return fallback_home(data)


def generate_party(data: dict) -> dict:
    prompt = f"Create a party budget plan. User data: {json.dumps(data)}"
    try:
        return _normalize(_call(prompt), "party", float(data["budget"]))
    except Exception:
        return fallback_party(data)


def generate_jewelry(data: dict, image_bytes: bytes | None = None, mime_type: str | None = None) -> dict:
    prompt = f"Create a jewelry recommendation plan for the occasion and style. User data: {json.dumps(data)}. If an outfit image is supplied, use it only for broad color/style coordination."
    try:
        return _normalize(_call(prompt, image_bytes, mime_type), "jewelry", float(data["budget"]))
    except Exception:
        return fallback_jewelry(data)
